dist: trusty
sudo: required
services:
- docker
language: node_js
node_js:
- 8.7.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-\\d+$/"
env:
  global:
  - NPM_REGISTRY=https://atomist.jfrog.io/atomist/api/npm/npm-dev-local
  - secure: rdOrSGj3eOCRUEXsKva70Gl5i+LKsGG7gmJe/wH3NT7gtIEZ3UOmDLohNQsJrqV13mJhb3ywgk5HYW/XVreYyrJMSmryjI52utkRxeogFjJ4DtaExQEVu2Ah8BIfzarDj+1bkTV+llwIrVjKI/IzyyNWkaxcfQXV9Jro48Zyieh5kL+2pDheklvJS9quG+E3rF67V5OunZUwrSYEgs5PjggH+AgbdXvzOHHMtcxfHIAMErDSQ9JCK1aDsmIMJMgcRRug5pEt0bGhyM+zPbut9jAY3GtvEqsgdwoj9WfvxkFOEJr8q0yLGfQ3aHIPGb4tNZbUNiJ46+I0z/CeDJNLwMijuD4YU/rwrPtKxoniAVzKWBgOEJpMYfcqzO/kYB+FCBHAhag2GpL5vlu4hT1SMg3QacDfOl4+H3K+kecWiC6uLltWAcbJ39N4KQdwSnDESEU70EJe2oW5VMeXjv5QsfUhOwATmFaADgkvnzZv+lyOP7T41BbFBcbval+ONE7TqFxX0/XGOQDxTElmT4viXEgYlXvMYhHy3VV1k6CTUWUjo7EQR1UUo/nwV4tTIxzcSCqqPDv8OfFH3DLhsdfgAdu0FiLEHu2zYMxTpivD+uee5WX8DeyaiJ22kpJQ8gEF2KsDftKdNOLi2aYVR1mYZLWUoh2ty39khuCvWLh+iEY=
  - secure: DJpGXA4V5EEkLDjYPG8Eqi+Cr+Y4v887dUmVD5N5FlBWM0g1PZf98I9+l9KQ42RjREbrUPNR5/x7AvGYnxmtyxXy3gPkzEuZ6XskZrTaWcaRFxz+b7bVZhm+o3Xmp43mZoRJJw26BHiluFRCVdTuNxjmvnflE+SrV55FmDgTMihZV/uQl5yMQvIflZQFdMSgSEnbn4ikMkNOxhAgATzO0y5JlnzVxXgx5gD9JkRw4XqttEYkSCaDi4p4+b9olXDGIq4sXwqK1yH9cilCBQqDBW8duQ0kXw/Wh4/nUh0BJ0/EMQ7USX/yxTK3CxzHIixGeInOgh72uIl3R4hmrNaCdQRskbZlVo7gCt0RhTUlDQWhJvQu5GOg2ILbfUZbYtna8LrVkSEVxckayogkMFSXTbkZxtEkgNceXPZRuqX+n+O+fCg9zW5fLbd1jxHzAuQPK3LFc/Te6+2TNIvXiih5yAqoftMkYnqTns/Ae5WTnR1spMB/nXZbcEjW70RXNcUVQogSJ9IoqPYBiCKEcKZkDVedaN1YTDNVDPjQxDZy3F4EW1HVHt1kNqmAW70s2skpC3UsoWYIVJAt5zQT60RpZwpARy1vwOjPE5NVsHZdSFbwPh7g81njkXpoWyKhWkyEVFWR4PdNs79VQZz09iJD40YIxNY/7SKuToSR2Bbokqc=
  - secure: yGZhlw6TDOa2I3H56qinn32v5WrB1aUe1YhICGMxoy3k5RvXrng7/wX58XmleoMg8GM9vQ8KqUw2UxwbtWixlUNRg/voidRSlruJ2lB8h+DzGUilJgOvRCb5mmMawVdD+Hp7EUwcT06BbQEf+XXT2TNrCKUuT3Q7TTHZbgVl1JT2DhBoH7cTgEAgPSHFCwa54lU0m2Wgos5FJK6Rpe83Auia2mEQZM3sabFaUmUunYQTy2qimPG/MnJKug7KtWJ1GziFIyFLfagm9o+iiNtIbyKZvY52Rcvojonxtd3rFQLUgut57mCK5dFTKa0oZIT2n/RyJHRCM+7frFjzcph//wWzx9P5VZ+UWQSFcaUw1TSLHVd2jfmqNSMsFF+kgGmibzpqeMY9ojJMEdp6qBD0FF86fgmF8ekZvGymMdKrlJKxJPu/JXBuSas0ZHKWIJIbymZFzHl1nz7+/93A9XTYlLP/M7+Er78wUdVYsTLegxbhyJ8wgNC4bSF3GQwKfqoLPlQ0A/X+Ym4nQTpmHwubVuX79XeUgfm+8125mIHXCS5UTSAOjmysZAa/4oHkQojGzW38bviKR2KOJ7yVzMwT06Acmv0j5hjse8LeRXGj0oMAgy3eDekFvPHiT+4vz6gYvAj2z8tMoapkEI+PKfhVIVidU2sTGgUnS8AWAvMbDmg=
  - secure: TsBE2lsl4HkrY1kauYfgTxaco/RGkgUN54FPg4E72qJ8ymgjcgZTrTEDA7DqH5hhX9OEDkM+gty86k8lQZnWcICzepPkYErfoGLuzbcZyoHfBERdxrTxAA4k+pCQihQTi/75CHrX15qzV1Uw4eAIQvGiED4mdK9fZbvwbgIUkX0x94/kxfT7TzfyDxLIrMnl5jrY7t5bM12o4PkUT0qenlRUvuwwkCs65YsEdPSg3yTEAbVaM3j5YEqnn28clydE14orlWSNq2OgLoXJIOhFxWWfztoXE3gPe6AVrt9TnItxPC8UMBK2zNML1cTFUkfjnMHLCjXexa8iU/3vlxPeYSDrmevkxU941zha6ZM6d11Cfed6YJCJynYEYjvCz3MQlSsog+L7oJfsE9xJj6paAWToShLUgJEuRCaTZGlfbh8xGvUrPLJHY0sTkkOEB0gZGC4AJv77vn2zBoHMLkjLBpSjRGBfUCN3CkrpABpe3JT8bzKSjWSnlnoIgRiDcxS4zKqRz4UkZeGOeYEfh9b/JPan3440WJuk4e/cclcTGtAx263+Pzv0r+fyo6yU98ewk99s94SZ/ImFVNfSFaZxa8VmNeijNFqPEtKlrVmIdvjWEz2Zd6Eguss79rkM7uHHeSZ2R+hb0bY/DgTxzIB/NpK5dc0+AAexGc9tIAEEJr8=
  - secure: ka/IgGCtDjppoGaFAtj4z5o9P5LECKG3RPF/G0svkDUcrToaunnOqJv5rhf1Clf7QK1cZPGbNUBMlDCygBU6U7AA6MC05V67p3tn4dbVcLuJQvGJDvw8jCXPts5/5meDrLrR/I7+QJLtBGjHA4kkSlQVQGowJXWU2zoP6xbG7NoIATtygQzemlTN0xPhw19AQY2zoPATfXf7Y6O84VCx1Kvcbl1wJL055Co3x+6fb0Uw8K/AQiQRtD/3R5jHs4fZZG4gQRHG/BkDjyU1yo1NapKL1xOJvUGdzbo2ijUiWf98qbx2KcUCOeC3U1/eHSs7NkdPN8yT90FUtt5kGQa1Eu037jtBpbhvbxss84chJ1GA6yKHjByeilW/Tj69WJcq0Pp1xdu+XGjsZ+uhDL0cwZM+g+k/qFenTeFD6PMKcQvp7ytD6gsfH3sFrKVLZNzCdYVal87XLJuYemTo18Nr/mYPBYtg9qtXlDL5jdxH8fN0xJugL0Mqyn/5RHMV241+z1mKZXq2o22HryJ5+x2luHeR8G3hEVrj+ZJzDN7vy9lJAJinV1p7v2VK9Z1TF7+UzDe6NKtbXDmi1GXzm2bR65u2KFSZYTJd16OqX+cH1BAz6yJMI/fGAgww10/3qUA6gfuzerspDcnFy7xZaglLzovAoJoikJ7hgCoLqx0oiPo=
before_install:
- openssl aes-256-cbc -K $encrypted_195b2e60f131_key -iv $encrypted_195b2e60f131_iv
  -in scripts/.npmrc.enc -out $HOME/.npmrc -d
#- wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key |
#  sudo apt-key add -
#- echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
#- sudo apt-get update
#- sudo apt-get install cf-cli
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.npm"
